// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MappingCreater is an autogenerated mock type for the MappingCreater type
type MappingCreater struct {
	mock.Mock
}

// CreateMapping provides a mock function with given fields: imageID, postID
func (_m *MappingCreater) CreateMapping(imageID int, postID int) (int, error) {
	ret := _m.Called(imageID, postID)

	if len(ret) == 0 {
		panic("no return value specified for CreateMapping")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (int, error)); ok {
		return rf(imageID, postID)
	}
	if rf, ok := ret.Get(0).(func(int, int) int); ok {
		r0 = rf(imageID, postID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(imageID, postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMappingCreater creates a new instance of MappingCreater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMappingCreater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MappingCreater {
	mock := &MappingCreater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
