// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import (
	models "url-shortener/pkg/models"

	mock "github.com/stretchr/testify/mock"
)

// ImageGetterAll is an autogenerated mock type for the ImageGetterAll type
type ImageGetterAll struct {
	mock.Mock
}

// GetAllImages provides a mock function with given fields:
func (_m *ImageGetterAll) GetAllImages() ([]models.Image, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllImages")
	}

	var r0 []models.Image
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Image, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Image); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Image)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewImageGetterAll creates a new instance of ImageGetterAll. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageGetterAll(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImageGetterAll {
	mock := &ImageGetterAll{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
