// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ImageDeleter is an autogenerated mock type for the ImageDeleter type
type ImageDeleter struct {
	mock.Mock
}

// DeleteImage provides a mock function with given fields: id
func (_m *ImageDeleter) DeleteImage(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewImageDeleter creates a new instance of ImageDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImageDeleter {
	mock := &ImageDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
