// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// ImageCreater is an autogenerated mock type for the ImageCreater type
type ImageCreater struct {
	mock.Mock
}

// CreateImage provides a mock function with given fields: image, created
func (_m *ImageCreater) CreateImage(image []byte, created time.Time) (int, error) {
	ret := _m.Called(image, created)

	if len(ret) == 0 {
		panic("no return value specified for CreateImage")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, time.Time) (int, error)); ok {
		return rf(image, created)
	}
	if rf, ok := ret.Get(0).(func([]byte, time.Time) int); ok {
		r0 = rf(image, created)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte, time.Time) error); ok {
		r1 = rf(image, created)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewImageCreater creates a new instance of ImageCreater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageCreater(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImageCreater {
	mock := &ImageCreater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
