// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// PostCreater is an autogenerated mock type for the PostCreater type
type PostCreater struct {
	mock.Mock
}

// CreatePost provides a mock function with given fields: title, content, created
func (_m *PostCreater) CreatePost(title string, content string, created time.Time) (int, error) {
	ret := _m.Called(title, content, created)

	if len(ret) == 0 {
		panic("no return value specified for CreatePost")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, time.Time) (int, error)); ok {
		return rf(title, content, created)
	}
	if rf, ok := ret.Get(0).(func(string, string, time.Time) int); ok {
		r0 = rf(title, content, created)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string, string, time.Time) error); ok {
		r1 = rf(title, content, created)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPostCreater creates a new instance of PostCreater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostCreater(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostCreater {
	mock := &PostCreater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
