// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PostDeleter is an autogenerated mock type for the PostDeleter type
type PostDeleter struct {
	mock.Mock
}

// DeletePost provides a mock function with given fields: id
func (_m *PostDeleter) DeletePost(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPostDeleter creates a new instance of PostDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostDeleter {
	mock := &PostDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
